### ISSUE TITLE
Possible Implementation

### ISSUE THREAD

**Issue by johnchristofis** [PeoplePerHour/candidate-tests#9]
Is it feasible to approach this by creating an interface with the **CRUD operations** + **transactions** and seperate ConnectionManager classes that implement this interface for every RDBMS (e.x ConnectionManagerMySQL, ConnectionManagerPostgreSQL, ConnectionManagerMsSQL etc). As a result, the actual code to perform and execute queries and eliminating SQL injection for each RDBMS will be placed in every ConnectionManager class.

Thank you in advance.

**Comment by tavantzo** [comment]
@johnchristofis Hi John. 

Sorry for the delayed response.

Well, it's would be a bit different than I had mind but it won't count as a wrong implementation.
A different way of thinking is always welcome.
Please go ahead and Implement this as you want. 

Kind Regards
George

**Comment by johnchristofis** [comment]
Hi George,

thank you for your feedback. So if I understand correctly you would like something like the following zip archive. Did I misunderstood something?

[johnchristofis.zip](https://github.com/PeoplePerHour/candidate-tests/files/1777483/johnchristofis.zip)


Thank you.

**Comment by tavantzo** [comment]
@johnchristofis More or less. Please provide any code in a PR for us to review.
